# Generated by Django 2.2.27 on 2022-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
