# Generated by Django 3.2 on 2022-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0002_auto_20220419_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainput',
            name='run_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datainput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
